import type { Slide, TemplateStyle } from '@/shared/types/slide'

export const SAMPLE_SLIDES: Record<TemplateStyle, Slide> = {
  clean: {
    id: 'sample-clean',
    type: 'cover',
    headline_label: '트렌드',
    headline: '2025 디자인 트렌드',
    subtext: '올해 주목해야 할 디자인 트렌드를 소개합니다',
  },
  minimal: {
    id: 'sample-minimal',
    type: 'cover',
    headline_label: '비즈니스',
    headline: '성공하는 스타트업의 비밀',
    subtext: '빠르게 성장하는 스타트업들의 공통점을 분석했습니다',
  },
  bold: {
    id: 'sample-bold',
    type: 'cover',
    headline_label: '혁신',
    headline: 'AI 시대의 새로운 기회',
    subtext: '인공지능 기술이 만들어가는 미래를 탐험해보세요',
  },
  elegant: {
    id: 'sample-elegant',
    type: 'cover',
    headline_label: '라이프스타일',
    headline: '우아한 일상의 발견',
    subtext: '특별한 순간을 더욱 특별하게 만드는 방법',
  },
  premium: {
    id: 'sample-premium',
    type: 'cover',
    headline_label: '프리미엄',
    headline: '럭셔리 브랜드 트렌드',
    subtext: '고급스러움을 정의하는 새로운 기준',
  },
  toss: {
    id: 'sample-toss',
    type: 'cover',
    headline_label: '금융',
    headline: '스마트한 자산 관리',
    subtext: '당신의 금융 생활을 더 쉽고 편리하게',
  },
  magazine: {
    id: 'sample-magazine',
    type: 'cover',
    headline_label: '특집',
    headline: '현대인의 필수 독서',
    subtext: '지금 읽어야 할 베스트셀러 도서 추천',
  },
  blueprint: {
    id: 'sample-blueprint',
    type: 'cover',
    headline_label: '테크',
    headline: '개발자를 위한 도구',
    subtext: '생산성을 높이는 필수 개발 도구 소개',
  },
}

export const SAMPLE_CONTENT_SLIDES: Record<string, Slide> = {
  'content': {
    id: 'sample-content',
    type: 'content',
    headline: '핵심 내용',
    body: '카드뉴스의 주요 메시지를 효과적으로 전달하는 가장 기본적인 레이아웃입니다.',
    emphasis: '간결하고 명확한 메시지',
  },
  'content-stat': {
    id: 'sample-stat',
    type: 'content-stat',
    headline: '만족도',
    emphasis: '95%',
    body: '사용자들이 우리 서비스에 높은 만족도를 보이고 있습니다',
  },
  'content-quote': {
    id: 'sample-quote',
    type: 'content-quote',
    body: '디자인은 단순히 예쁜 것이 아니라 어떻게 작동하는가에 대한 것입니다',
    headline: '- 스티브 잡스',
  },
  'content-badge': {
    id: 'sample-badge',
    type: 'content-badge',
    badge_text: 'TIP',
    headline: '전문가의 조언',
    body: '작은 습관의 변화가 큰 차이를 만듭니다. 매일 5분씩 투자해보세요.',
  },
  'content-steps': {
    id: 'sample-steps',
    type: 'content-steps',
    headline: '성공적인 시작을 위한 3단계',
    step1: '목표를 명확하게 설정하기',
    step2: '실행 가능한 계획 수립하기',
    step3: '꾸준히 실천하고 개선하기',
  },
  'content-list': {
    id: 'sample-list',
    type: 'content-list',
    headline: '필수 체크리스트',
    item1: '사용자 요구사항 분석',
    item2: '경쟁사 리서치 진행',
    item3: '프로토타입 제작',
    item4: '사용자 테스트 실시',
    item5: '피드백 반영 및 개선',
  },
  'content-split': {
    id: 'sample-split',
    type: 'content-split',
    headline: '변화의 순간',
    left_title: 'Before',
    left_body: '복잡하고 비효율적인 프로세스',
    right_title: 'After',
    right_body: '간결하고 효율적인 워크플로우',
  },
  'content-highlight': {
    id: 'sample-highlight',
    type: 'content-highlight',
    headline: '가장 중요한 메시지',
    body: '지금 바로 시작하세요. 완벽한 순간을 기다리지 마세요.',
  },
  'content-image': {
    id: 'sample-image',
    type: 'content-image',
    headline: '시각적 스토리텔링',
    body: '이미지와 함께 전달하는 강력한 메시지',
    image_url: '',
  },
  'content-grid': {
    id: 'sample-grid',
    type: 'content-grid',
    headline: '핵심 기능 4가지',
    item1: '빠른 속도',
    item2: '높은 품질',
    item3: '쉬운 사용',
    item4: '저렴한 가격',
  },
  'content-bigdata': {
    id: 'sample-bigdata',
    type: 'content-bigdata',
    headline: '누적 사용자',
    bigdata_number: '1,000,000',
    bigdata_unit: '명',
    body: '전 세계 사용자들이 신뢰하는 서비스',
  },
  'content-fullimage': {
    id: 'sample-fullimage',
    type: 'content-fullimage',
    headline: '새로운 시작',
    image_url: '',
  },
  'cta': {
    id: 'sample-cta',
    type: 'cta',
    headline: '지금 바로 시작하세요',
    cta_text: '무료로 시작하기',
    tag1: '#디자인',
    tag2: '#카드뉴스',
    tag3: '#템플릿',
  },
}
