import type { TemplateConfig, TemplateStyle } from '@/shared/types/slide'

export const TEMPLATES: Record<TemplateStyle, TemplateConfig> = {
  clean: {
    name: 'Clean',
    bg: '#F5F5F0',
    text: '#1a1a1a',
    accent: '#8BC34A',
    subtext: '#555',
    cardBg: '#FFFFFF',
    font: "Georgia, serif",
    headFont: "'Playfair Display', Georgia, serif",
  },
  minimal: {
    name: 'Minimal',
    bg: '#FFFFFF',
    text: '#111',
    accent: '#2D63E2',
    subtext: '#666',
    cardBg: '#FAFAFA',
    font: "'DM Sans', sans-serif",
    headFont: "'DM Sans', sans-serif",
  },
  bold: {
    name: 'Bold',
    bg: 'linear-gradient(135deg, #1a0533 0%, #2d1060 100%)',
    text: '#FFFFFF',
    accent: '#C084FC',
    subtext: '#C4B5FD',
    cardBg: 'rgba(255,255,255,0.06)',
    font: "'Bebas Neue', Impact, sans-serif",
    headFont: "'Bebas Neue', Impact, sans-serif",
  },
  elegant: {
    name: 'Elegant',
    bg: '#1a1612',
    text: '#F5ECD7',
    accent: '#D4AF37',
    subtext: '#B8A98A',
    cardBg: 'rgba(255,255,255,0.04)',
    font: "'Cormorant Garamond', Georgia, serif",
    headFont: "'Cormorant Garamond', Georgia, serif",
  },
  premium: {
    name: 'Premium',
    bg: '#0A0A0F',
    text: '#FFFFFF',
    accent: '#E8B4B8',
    subtext: '#9CA3AF',
    cardBg: 'rgba(255,255,255,0.03)',
    font: "'Inter', -apple-system, sans-serif",
    headFont: "'Inter', -apple-system, sans-serif",
  },
  toss: {
    name: 'Toss',
    bg: '#191F28',
    text: '#FFFFFF',
    accent: '#3182F6',
    subtext: '#8B95A1',
    cardBg: '#252D3A',
    font: "-apple-system, BlinkMacSystemFont, sans-serif",
    headFont: "-apple-system, BlinkMacSystemFont, sans-serif",
  },
  magazine: {
    name: 'Magazine',
    bg: '#F8F4EE',
    text: '#1C1C1C',
    accent: '#E84040',
    subtext: '#7A6F6A',
    cardBg: '#FFFFFF',
    font: "'Merriweather', Georgia, serif",
    headFont: "'Libre Baskerville', Georgia, serif",
  },
  blueprint: {
    name: 'Blueprint',
    bg: '#0D1B2A',
    text: '#E0E7FF',
    accent: '#38BDF8',
    subtext: '#64748B',
    cardBg: '#1B2838',
    font: "'JetBrains Mono', monospace",
    headFont: "'JetBrains Mono', monospace",
  },
} as const
